# THIS FILE IS AUTOGENERATED USING `mix ash.formatter`
# DONT MODIFY IT BY HAND
locals_without_parens = [
  base: 1,
  before_request: 1,
  endpoint: 1,
  endpoint: 2,
  entity_path: 1,
  field: 1,
  field: 2,
  fields_in: 1,
  finch: 1,
  get_endpoint: 2,
  get_endpoint: 3,
  path: 1,
  write_entity_path: 1,
  write_path: 1
]

[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: locals_without_parens,
  export: [
    locals_without_parens: locals_without_parens
  ]
]
